/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgetpassword` | `/forgetpassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/otp` | `/otp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/resetpassword` | `/resetpassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/addRide` | `/addRide`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/allRides` | `/allRides`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/qr` | `/qr`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/rideDetails/[id]` | `/rideDetails/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/forgetpassword` | `/forgetpassword`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/otp` | `/otp`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/resetpassword` | `/resetpassword`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/addRide` | `/addRide`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/allRides` | `/allRides`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/qr` | `/qr`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(screens)'}/rideDetails/[id]` | `/rideDetails/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/forgetpassword${`?${string}` | `#${string}` | ''}` | `/forgetpassword${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/otp${`?${string}` | `#${string}` | ''}` | `/otp${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/resetpassword${`?${string}` | `#${string}` | ''}` | `/resetpassword${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/addRide${`?${string}` | `#${string}` | ''}` | `/addRide${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/allRides${`?${string}` | `#${string}` | ''}` | `/allRides${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/qr${`?${string}` | `#${string}` | ''}` | `/qr${`?${string}` | `#${string}` | ''}` | `${'/(screens)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgetpassword` | `/forgetpassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/otp` | `/otp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/resetpassword` | `/resetpassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/addRide` | `/addRide`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/allRides` | `/allRides`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/qr` | `/qr`; params?: Router.UnknownInputParams; } | { pathname: `${'/(screens)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `${'/(screens)'}/rideDetails/${Router.SingleRoutePart<T>}` | `/rideDetails/${Router.SingleRoutePart<T>}` | { pathname: `${'/(screens)'}/rideDetails/[id]` | `/rideDetails/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
